# Generated by Django 5.2.4 on 2025-10-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='菜品名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='价格')),
                ('category', models.CharField(choices=[('主菜', '主菜'), ('汤类', '汤类'), ('小吃', '小吃'), ('甜点', '甜点'), ('饮料', '饮料')], max_length=20, verbose_name='分类')),
                ('image', models.ImageField(upload_to='images/', verbose_name='图片URL')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '菜单项',
                'verbose_name_plural': '菜单项',
                'ordering': ['category', 'name'],
            },
        ),
    ]
