# Generated by Django 5.2.4 on 2025-10-30 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='menuOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='订单号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('table_num', models.IntegerField(verbose_name='桌号')),
                ('status', models.CharField(choices=[('ordered', '已下单'), ('served', '已结单'), ('cancelled', '已取消')], default='ordered', max_length=20, verbose_name='订单状态')),
            ],
        ),
        migrations.CreateModel(
            name='midOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('discount', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='折扣')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='单价')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小计')),
                ('status', models.CharField(choices=[('pending', '已下单'), ('cooking', '制作中'), ('served', '已上菜'), ('cancelled', '已取消'), ('finished', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menuorder')),
            ],
        ),
    ]
