# Generated by Django 5.2.4 on 2025-10-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuorder_midorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='midorder',
            name='table_num',
            field=models.IntegerField(default=1, verbose_name='桌号'),
            preserve_default=False,
        ),
    ]
