# Generated by Django 5.2.4 on 2025-11-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_midorder_table_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuorder',
            name='free',
            field=models.BooleanField(default=True, verbose_name='是否空桌'),
        ),
    ]
