# Generated by Django 5.2.4 on 2025-11-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuorder_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuorder',
            name='status',
            field=models.CharField(choices=[('ordered', '已下单'), ('served', '已上菜'), ('finshed', '已结算'), ('cancelled', '已取消')], default='ordered', max_length=20, verbose_name='订单状态'),
        ),
    ]
