# Generated by Django 5.2.4 on 2025-11-11 11:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menuorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='midorder',
            name='midOrderId',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
