# Generated by Django 5.2.4 on 2025-11-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_midorder_midorderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midorder',
            name='status',
            field=models.CharField(choices=[('pending', '已下单'), ('cooking', '制作中'), ('served', '已上菜'), ('cancelled', '已取消'), ('finshed', '已完成')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
